services:
  postgres:
    build: ./db
    image: zikarimovlt/test-db
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: ./api
    image: zikarimovlt/test-api
    container_name: api
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: 5432
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: