# service-account.yaml
apiVersion: v1                            # Версия API для ServiceAccount
kind: ServiceAccount                      # Тип ресурса - сервисный аккаунт
metadata:                                 # Метаданные ресурса
  name: gitlab-ci                         # Имя сервисного аккаунта
  namespace: default                      # Namespace где создается аккаунт
---                                       # Разделитель между ресурсами в одном файле
apiVersion: rbac.authorization.k8s.io/v1  # Версия API для RBAC
kind: ClusterRoleBinding                  # Тип ресурса - привязка роли на уровне кластера
metadata:                                 # Метаданные привязки
  name: gitlab-ci                         # Имя привязки роли
roleRef:                                  # Ссылка на роль которую назначаем
  apiGroup: rbac.authorization.k8s.io     # API группа для ролей
  kind: ClusterRole                       # Тип роли - кластерная роль
  name: cluster-admin                     # Имя роли (полные права администратора)
subjects:                                 # Субъекты которым назначается роль
- kind: ServiceAccount                    # Тип субъекта - сервисный аккаунт
  name: gitlab-ci                         # Имя сервисного аккаунта
  namespace: default                      # Namespace где находится аккаунт