apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-documents-ceph-pvc
  namespace: otus
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
